# Generated by Django 4.2.20 on 2025-08-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
    ]
